image: docker:latest
services:
  - docker:dind

before_script:
- docker info

variables:
  REGISTRY: "registry.vshn.net"
  IMAGE_NAME: "vshn/wrestic"

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - docker build -t ${REGISTRY}/${IMAGE_NAME} .
    - docker push ${REGISTRY}/${IMAGE_NAME}
  tags:
    - dockerbuild
  only:
    - dev

build:tag:
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY
    - docker build -t ${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker push ${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG}
  only:
    - tags
  tags:
    - dockerbuild

